const restaurants = (req, res) => {
    res.send([
        {
            id: 1,
            name: "The Dark Roast",
            cloudinaryImageId: "mzdetw2s1ihmpiegkhyl",
            locality: "Market Plaza",
            areaName: "Delhi",
            costForTwo: "₹260 for two",
            cuisines: [
                "Italian-American",
                "Continental",
                "Burgers",
                "Pizzas",
                "Pastas",
                "Asian Fusion",
                "Beverages",
                "Healthy Options",
            ],
            avgRating: 3.2,
            avgRatingString: "3.2",
            totalRatingsString: "10K+",
            isOpen: true,
            aggregatedDiscountInfoV3: {
                header: "₹100 OFF",
                subHeader: "ON ORDERS ABOVE ₹199",
                discountTag: "LIMITED TIME DEAL",
            },
        },
        {
            id: 2,
            name: "Crust Corner",
            cloudinaryImageId: "hgte5u6o5gvvluewdwet",
            locality: "Urban Square",
            areaName: "Sector 10",
            costForTwo: "₹270 for two",
            cuisines: ["Pizzas", "Burgers", "Fast Food", "Italian", "Grill", "Tandoor"],
            avgRating: 4.2,
            veg: true,
            avgRatingString: "4.2",
            totalRatingsString: "8K+",
            isOpen: true,
        },
        {
            id: 3,
            name: "Spicy Bucket",
            cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
            locality: "Food Hub Mall",
            areaName: "Sector 15",
            costForTwo: "₹420 for two",
            cuisines: ["Burgers", "American", "Grill", "Fast Food"],
            avgRating: 4.9,
            avgRatingString: "4.9",
            totalRatingsString: "5K+",
            isOpen: true,
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UP TO ₹50",
            },
        },
        {
            id: 4,
            name: "Burger Haven",
            cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
            locality: "Central Square Mall",
            areaName: "Sector 15",
            costForTwo: "₹330 for two",
            cuisines: ["American", "Grill"],
            avgRating: 4,
            avgRatingString: "4.0",
            totalRatingsString: "9K+",
            isOpen: true,
            aggregatedDiscountInfoV3: {
                header: "SPECIAL MENU",
                subHeader: "@ ₹129 PER ITEM",
            },
        },
        {
            id: 5,
            name: "Momolicious",
            cloudinaryImageId: "0984acc0ed7b914206dbbcb90297becc",
            locality: "Sector 14",
            areaName: "Sector 14",
            costForTwo: "₹280 for two",
            cuisines: ["Tibetan", "Chinese", "Fast Food", "Continental", "Beverages"],
            avgRating: 4.8,
            avgRatingString: "4.8",
            totalRatingsString: "2K+",
            isOpen: true,
            aggregatedDiscountInfoV3: {
                header: "SAVE 60%",
                subHeader: "UP TO ₹120",
            },
        },
        {
            id: 6,
            name: "Chai Break",
            cloudinaryImageId: "2beebd3688e63e027ee8a11c1c8a72c8",
            locality: "Old Market",
            areaName: "Sector 15",
            costForTwo: "₹230 for two",
            cuisines: ["Bakery", "Chaat", "Tea & Snacks", "Desserts", "Street Food"],
            avgRating: 3.2,
            avgRatingString: "3.2",
            totalRatingsString: "2K+",
            textExtendedBadges: [
                {
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "Healthy Options Available",
                    fontColor: "#7E808C",
                },
            ],
            isOpen: true,
            aggregatedDiscountInfoV3: {
                header: "SAVE 50%",
                subHeader: "UP TO ₹100",
            },
        },
        {
            id: 7,
            name: "Wrap ‘n Roll",
            cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
            locality: "City Centre",
            areaName: "Industrial Township",
            costForTwo: "₹220 for two",
            cuisines: ["Kebabs", "Fast Food", "Snacks", "North Indian", "Wraps"],
            avgRating: 3.9,
            avgRatingString: "3.9",
            totalRatingsString: "1.2K+",
            textExtendedBadges: [
                {
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "Healthy Options Available",
                    fontColor: "#7E808C",
                },
            ],
            isOpen: true,
            aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UP TO ₹100",
            },
        },
        {
            id: 8,
            name: "Nirula’s Deli",
            cloudinaryImageId: "whgmbmdif5udm6patgib",
            locality: "Downtown Market",
            areaName: "Sector 15",
            costForTwo: "₹510 for two",
            cuisines: ["Burgers", "Desserts", "North Indian", "Italian", "Ice Cream"],
            avgRating: 3,
            avgRatingString: "3",
            totalRatingsString: "200+",
            textExtendedBadges: [
                {
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "Guilt-Free Choices",
                    fontColor: "#7E808C",
                },
            ],
            isOpen: true,
        },
        {
            id: 9,
            name: "Asia Chow",
            cloudinaryImageId: "6e97ac8f5c89213610309ef1940afa05",
            locality: "Parkside Avenue",
            areaName: "Sector 15",
            costForTwo: "₹310 for two",
            cuisines: ["Chinese", "Thai", "Asian Fusion"],
            avgRating: 4,
            avgRatingString: "4",
            totalRatingsString: "4.5K+",
            isOpen: true,
            aggregatedDiscountInfoV3: {
                header: "₹100 OFF",
                subHeader: "ON ORDERS ABOVE ₹200",
                discountTag: "SPECIAL OFFER",
            },
        },
        {
            id: 10,
            name: "Oven Story Pizza Co.",
            cloudinaryImageId: "f986df6f1a1fcf2ff24d2eaf44d570a7",
            locality: "Central Plaza",
            areaName: "New Industrial Township",
            costForTwo: "₹410 for two",
            cuisines: ["Italian", "Pizza", "Beverages"],
            avgRating: 3.7,
            avgRatingString: "3.7",
            totalRatingsString: "900+",
            isOpen: true,
            aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ON ORDERS ABOVE ₹1099",
                discountTag: "FLAT DEAL",
            },
        },
        {
            id: 11,
            name: "Slice Hut",
            cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
            locality: "Metro Mall",
            areaName: "Industrial Zone",
            costForTwo: "₹340 for two",
            cuisines: ["Pizza"],
            avgRating: 3.6,
            avgRatingString: "3.6",
            totalRatingsString: "1.2K+",
            isOpen: true,
        },
    ]);
};

module.exports = {
    restaurants,
};

